function createfigure(x1, y1, s1, c1)
%CREATEFIGURE(X1,Y1,S1,C1)
%  X1:  scatter x
%  Y1:  scatter y
%  S1:  scatter s
%  C1:  scatter c
 
%  Auto-generated by MATLAB on 11-Nov-2006 18:23:22
 
%% Create figure
figure1 = figure;
 
%% Create axes
load iterdata;
x = iterdata(:,1);
y = iterdata(:,7);
 
%% Create scatter
scatter(x,y,'.','k');
 
xlabel('Number of Variables * Number of Instructions','fontsize',12);
ylabel('Number of Iterations','fontsize',12);

saveas(gcf,'../../figures/iter_linear.eps','eps');
